In [2]:
import numpy as np

In [6]:
class update:
    #Probably best if we change the space matrix to store the coefficients rather than the
    #parameters of the materials since that is what we need
    
    #Define update function for the E field
    def update_E_tot(E, H, space, delta_t, delta_x):
        #Calculate needed coefficients (found on pg 91 of Numerical EM)
        #More efficient to input these numbers, but for now I'll leave the calculations here
        #Currently 2D
        c1 = np.divide(np.subtract(np.multiply(2, space[:,:,0]), np.multiply(space[:,:,1], delta_t)
                                  ), np.add(np.multiply(2, space[:,:,0]), 
                                           np.multiply(space[:,:,1], delta_t)))
        
        c2 = np.divide(2*delta_t, np.add(np.multiply(2, space[:,:,0]), 
                                           np.multiply(space[:,:,1], delta_t)))
        
        #Approximate the curl
        
        #Curl in the X direction
        curl_x = np.divide(np.subtract(H[:,:,2], np.roll(H[:,:,2], 1, axis = 0)), delta_x)
        
        #Curl in the Y direction
        curl_y = np.divide(np.subtract(np.roll(H[:,:,2], 1, axis = 1), H[:,:,2]), delta_x)
        
        #Curl in the Z direction
        curl_z = np.divide(np.add(np.subtract(H[:,:,1], np.roll(H[:,:,1], 1, axis = 1)),
                                 np.subtract(np.roll(H[:,:,0], 1, axis=0), H[:,:,0])), delta_x)
        
        #Calculate the new E values
        #Doing components 1 by 1 since numpy is much better with 2D arrays and so that we don't
        #have to first make a 3D curl matrix
        
        #New X component
        E[:,:,0] = np.add(np.multiply(c1, E[:,:,0]), np.multiply(c2, curl_x))
        
        #Y component
        E[:,:,1] = np.add(np.multiply(c1, E[:,:,1]), np.multiply(c2, curl_y))
        
        #Z component
        E[:,:,2] = np.add(np.multiply(c1, E[:,:,2]), np.multiply(c2, curl_z))
        
        return E
    
    #Define update function for H
    def update_H(H, E, space, delta_x, delta_t):
        #Calculate needed coefficients (found on pg 91 of Numerical Electrodynamics)
        #More efficient to input these numbers, but for now I'll leave the calculations here
        #Currently 2D
        mu = #Whatever (doesn't matter since we're changing the location of this calculation)
        c1 = np.divide(np.subtract(np.multiply(2, mu), np.multiply(space[:,:,2], delta_t)
                                  ), np.add(np.multiply(2, mu), 
                                           np.multiply(space[:,:,2], delta_t)))
        
        c2 = np.divide(2*delta_t, np.add(np.multiply(2, mu), 
                                           np.multiply(space[:,:,2], delta_t)))
        
        #Approximate the curl
        
        #Curl in the X direction
        curl_x = np.divide(np.subtract(np.roll(E[:,:,2], -1, axis = 0), E[:,:,2]), delta_x)
        
        #Curl in the Y direction
        curl_y = np.divide(np.subtract(E[:,:,2], np.roll(E[:,:,2], -1, axis = 1)), delta_x)
        
        #Curl in the Z direction
        curl_z = np.divide(np.add(np.subtract(np.roll(E[:,:,1], -1, axis = 1), E[:,:,1]),
                                 np.subtract(E[:,:,0], np.roll(E[:,:,0], -1, axis=0))), delta_x)
        
        #Calculate the new H values
        #Doing components 1 by 1 since numpy is much better with 2D arrays and so that we don't
        #have to first make a 3D curl matrix
        
        #New X component
        H[:,:,0] = np.add(np.multiply(c1, H[:,:,0]), np.multiply(c2, curl_x))
        
        #Y component
        H[:,:,1] = np.add(np.multiply(c1, H[:,:,1]), np.multiply(c2, curl_y))
        
        #Z component
        H[:,:,2] = np.add(np.multiply(c1, H[:,:,2]), np.multiply(c2, curl_z))
        
        return H
    
    #Define function that enforces the PEC when the boundary is at the top of the matrix
    #Only applicable in the total field region
    def pec_minus_y(E, H, tang_direc):
        #Don't forget that each subregion overlaps by 1 index in all directions
        #So we need to set the 2nd highest row to zero
        
        #Determine normal direction
        norm_direc = 
        
        #tang_direc indicates the direction tangential to the surface
        #x=0, y=1, z=2
        E[1,:,tang_direc] = 0
        
        #Enforce the normal E boundary condition
        E[]
        
        #Enforce tangential H boundary condition
        
        #Enforce normal H boundary condition
        H[1,:,norm_direc] = 0
        
        return E
    
    #Define function that enforces the PEC when the boundary is at the bottom of the matrix
    #Only applicable in the total field region
    def pec_plus_y(E, tang_direc):
        #Don't forget that each subregion overlaps by 1 index in all directions
        #So we need to set the 2nd highest row to zero
        
        #tang_direc indicates the direction tangential to the surface
        #x=0, y=1, z=2
        E[-2,:,tang_direc] = 0
        
        return E
    
    #Define function that enforces the PEC when the boundary is on the left edge of the matrix
    #Only applicable in the total field region
    def pec_minus_x(E, tang_direc):
        #Don't forget that each subregion overlaps by 1 index in all directions
        #So we need to set the 2nd highest row to zero
        
        #tang_direc indicates the direction tangential to the surface
        #x=0, y=1, z=2
        E[:, 1, tang_direc] = 0
        
        return E
    
    #Define function that enforces the PEC when the boundary is on the right edge of the matrix
    #Only applicable in the total field region
    def pec_plus_x(E, tang_direc):
        #Don't forget that each subregion overlaps by 1 index in all directions
        #So we need to set the 2nd highest row to zero
        
        #tang_direc indicates the direction tangential to the surface
        #x=0, y=1, z=2
        E[:, -2,tang_direc] = 0
        
        return E
    
    #Define functions that allow for the transfer between total field and scattered field regions
    def scat2tot_E_plus_x(E, space, H_inc, c2):
        #Need a better name
        #c2 is the coefficient calculated in the update equations for E
        
        #Add in the incident wave terms on pg 161 of the Numerical EM book
        #Do 1 component at a time
        
        #X component
        E[:,1,0] = np.add(, )

In [5]:
A = np.arange(9).reshape((3,3))
print(A)
print(np.roll(A, 1, axis = 0))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [0 1 2]
 [3 4 5]]
